# fly.toml app configuration file generated for fragrant-bush-7090 on 2023-07-25T15:36:46-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fragrant-bush-7090"
primary_region = "yyz"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
